### PR TITLE
add matrix and riot

### PR DESCRIPTION
**Pull request by jcgruenhage**
drawing drawing

### CODE REVIEW

**Review by pkq — CHANGES_REQUESTED** [review]
Thanks for submitting these! Would you mind adding a brief description to the .json files so folks can get a sense of what these stickers represent?

**Comment by jcgruenhage** [comment]
Will do!

Until I get to it: the left one is for https://matrix.org/, a federated protocol for communication and the right one is https://riot.im/, a messenger built on top of it.

**Comment by jcgruenhage** [comment]
@pkq Is that okay now?

**Review by pkq — APPROVED** [review]

**Comment by pkq** [comment]
Thanks for contributing!

**Pull request merged**
