### PR TITLE
add naniar and visdat

### PR DESCRIPTION
**Pull request by njtierney**
visdat-logo
naniar-logo

### CODE REVIEW

**Comment by pkq** [comment]
@njtierney can you add the png file for visdat to the PR?

**Review by pkq — CHANGES_REQUESTED** [review]
@njtierney can you add the png file for visdat to the PR?

**Comment by njtierney** [comment]
Ooops! Sorry about that, how is that, @pkq ?

Cheers! :)

**Review by pkq — APPROVED** [review]
LGTM!

**Comment by njtierney** [comment]
Hooray!

**Pull request merged**
