### PR TITLE
Add r-datatable

### PR DESCRIPTION
**Pull request by mattdowle**
r-datatable

The creative process behind it :  Rdatatable/data.table#1237

### CODE REVIEW

**Comment by max-mapper** [comment]
I love the design process thread! I'll try to merge this soon

**Comment by ha0ye** [comment]
The URL for online ordering does not resolve for me -- fix please?

**Comment by mattdowle** [comment]
@ha0ye I just tried it and it works for me.  What happens when you try it - is there an error message?

**Comment by ha0ye** [comment]
@mattdowle Hmm - I got a DNS lookup failure when I tried from home yesterday, but seems ok at work right now. Will try again later this evening and see if there's an issue.

EDIT: working now... ¯\_(ツ)_/¯

**Pull request merged**
