### PR TITLE
Add BuffaloR

### PR DESCRIPTION
**Pull request by scottmmjackson**
buffalo-r

### CODE REVIEW

**Comment by scottmmjackson** [comment]
Noticed that my name has uppercase letters. Will fix soon.

**Comment by scottmmjackson** [comment]
Ready for review.

**Review by hexagontruth — APPROVED** [review]
You've got an illegal trailing slash in the JSON file but I'll allow it.

**Comment by scottmmjackson** [comment]
Are you referring to the meetup URL's forward slashes?

ECMA-404 section 9 states that the only characters that must be escaped are `\`, `"`, and two unicode control characters. Forward slashes are permitted at any point in a string.

If there is a problem I would like to fix it. Just let me know.

**Comment by hexagontruth** [comment]
Sorry lol no I meant a trailing comma in the JSON, not a trailing slash.

**Pull request merged**
