### PR TITLE
covid19

### PR DESCRIPTION
**Pull request by elsaburren**
hexagon covid19

Co-Authored-By: David Ardia <ardiad@users.noreply.github.com>
Co-Authored-By: Emanuele Guidotti <emanuele.guidotti@unine.ch>

### CODE REVIEW

**Review by hexagontruth — CHANGES_REQUESTED** [review]
You seem to have some sort of LaTeX-flavored JSON here lol can you possibly replace it with regular JSON? Also please remove the `order_online_url` I guess if you're not using it (and remember to remove the trailing comma on the previous line).

Also can you elaborate on what your relationship is with this project and logo and whether it's authorized, &c.? It's unclear what the connection of e.g. the two people mentioned in your description are, or the person mentioned in the author field in the JSON file. And a cursory search does not show me the logo being used anywhere etc.

Anyway if all that is resolved I for one am willing to commit this out of order, given its timeliness, etc.

**Comment by ArdiaD** [comment]
Hi @hexagrahamaton  
We are responsible for the datahub https://covid19datahub.io/.
We finished the logo today.
I will fix the json, sorry for that. We needed to rush. @ElsaBurren is is our team

**Comment by ArdiaD** [comment]
> hexagon covid19
> 
> Co-Authored-By: David Ardia [ardiad@users.noreply.github.com](mailto:ardiad@users.noreply.github.com)
> Co-Authored-By: Emanuele Guidotti [emanuele.guidotti@unine.ch](mailto:emanuele.guidotti@unine.ch)

@ArdiaD  @emanuele-guidotti

**Comment by ArdiaD** [comment]
> Hi @hexagrahamaton
> We are responsible for the datahub https://covid19datahub.io/.
> We finished the logo today.
> I will fix the json, sorry for that. We needed to rush. @ElsaBurren is is our team

@hexagrahamaton can you help me; sorry for that. I fixed the json. How can I fix now the pull request?

**Comment by elsaburren** [comment]
covid19.json is fixed

**Comment by ArdiaD** [comment]
> covid19.json is fixed

@hexagrahamaton is it ok?

**Review by hexagontruth — APPROVED** [review]
lgtm

**Pull request merged**
