### PR TITLE
Add FOLIO Project

### PR DESCRIPTION
**Pull request by dltj**
FOLIO Project logo

### CODE REVIEW

**Review by hexagontruth — CHANGES_REQUESTED** [review]
Hi — at least two things need to be addressed here:
1) The PNG does not seem to be transparent
2) The trailing slash in the JSON file is invalid
Thanks!

**Review by hexagontruth — CHANGES_REQUESTED** [review]
This is better and all but it seems like you just deleted the solid white without really adding a proper alpha layer, so the antialiasing is all weird, and will look awful on the site given the dark background etc.:
folio

Would it be possible to re-save the file using a proper alpha layer so it doesn't have these edge effects?

**Review by hexagontruth — APPROVED** [review]
:+1:

**Comment by hexagontruth** [comment]
I am reminded, by my similar mistake in another thread, that I meant "trailing comma" not "trailing slash." Tho you obviously understood what I meant since it was fixed.

**Comment by dltj** [comment]
Thank you—much appreciated.  And I should have paid attention to the editor's JSON validator before saving the first time.

**Pull request merged**
