### PR TITLE
add mangothecat

### PR DESCRIPTION
**Pull request by gingerbenw**
mangothecat

### CODE REVIEW

**Review by Ruxton — CHANGES_REQUESTED** [review]
@gingerbenw Is there a vector version of this hex?

**Comment by pkq** [comment]
@gingerbenw – Great sticker! If you can add a `.png` for this, I'd be happy to get it merged.

**Review by pkq — CHANGES_REQUESTED** [review]
@gingerbenw – Love the sticker! If you can add a vector version of this, I'd be happy to get it merged.

**Comment by gingerbenw** [comment]
Sorry for the insanely slow reply on this one guys! I am no longer with this company, and I could never get them to provide me an SVG version of the icon. I think it's safe to abandon this now.

**Pull request closed without merging**
