### PR TITLE
Add travis and JSON linting

### PR DESCRIPTION
**Pull request by wamserma**
This closes issue #107.

You definitely want to squash this PR when merging.

### CODE REVIEW

**Comment by Ruxton** [comment]
I don't disagree this is needed, but I think the running of the linter should go into the package.json alongside build and then CI can run that?

**Review by Ruxton — CHANGES_REQUESTED** [review]
move jsonlint to package.json and run it there? Possibly need to add it as a dependency too?

**Comment by wamserma** [comment]
I deliberately put it in a üre-build stage as it verifies that the inputs to the build are somewhat sane. Plus, the linter is in python (installed by apt to the build environment) and calling that from package.json might be kind of complicated. It would require definitely more than just putting in another dependency line.
Calling from build.js might technically be an option, but not logically. The current form of this PR helps identifying where things go wrong instead of just having the build fail.

**Comment by wamserma** [comment]
Closing due to age of PR.

**Pull request closed without merging**
