### PR TITLE
adding hexpace.net sticker market

### PR DESCRIPTION
**Pull request by HasseNasse**

### CODE REVIEW

**Comment by hexagontruth** [comment]
Hi this site no longer resolves at this URL — does it still exist?

**Comment by HasseNasse** [comment]
Yeah, they have changed the name to www.stickerdev.net.

**Comment by hexagontruth** [comment]
Thanks. That does look like a useful resource, but I have two main reservations about it:

1) Existing sticker links are to general-purpose sticker printers, not resellers of particular stickers (this is what the `order_online_url` is for in the sticker metadata).
2) It is not entirely clear what their IP claim to some of these designs are. Like, I am 100% sure they don't have the right to sell stickers with the AWS logo on them.

Can you shed any light on the business model here? Is this your company or do you have some connection with it?

**Comment by HasseNasse** [comment]
Unfortunately not, I'm just a frequent buyer. They do have a support page and we could forward the questions there, I suppose.

**Pull request closed without merging**
