### PR TITLE
Add Pulp hexagon.

### PR DESCRIPTION
**Pull request by ipanova**

### CODE REVIEW

**Comment by ipanova** [comment]
@maxogden @ha0ye any idea when this could be merged? thanks! :tada:

**Comment by Ruxton** [comment]
Is there a license for this? If Pulp is GPLv2, are the logos too?

**Comment by ipanova** [comment]
@Ruxton Hey, as per discussion with our legals we decided to leave this field blank, unlicensed.
I hope this is not a showstopper to merge the PR.

**Comment by ipanova** [comment]
@Ruxton please rebuild the site 🌟 🌴

**Pull request merged**
