### PR TITLE
add-dapperstats-logo

### PR DESCRIPTION
**Pull request by juniperlsimonis**
Adding logo for [DAPPER stats](http://www.dapperstats.com)

dapper_icon-36397

### CODE REVIEW

**Review by ha0ye — CHANGES_REQUESTED** [review]
Can you bring the json file name and links all into alignment? Maybe make everything “dapperstats.*”?

Also, MIT license is more suitable for code; would you be ok changing that to one of the CC licenses?

Once those are in, I can merge the PR.

**Comment by juniperlsimonis** [comment]
done! let me know if I need to edit anything else. 
also, just FYI, I followed the example linked to in the README (although clearly not perfectly) and it has a license that's MIT.

**Comment by ha0ye** [comment]
Hah, fair enough. The metadata file still lists `dapper.png`, but the file being uploaded is `dapperstats.png`. (And same for the .eps)

**Comment by juniperlsimonis** [comment]
aye, sorry! fixed!

**Review by ha0ye — APPROVED** [review]

**Pull request merged**
