### PR TITLE
add geobr hex sticker

### PR DESCRIPTION
**Pull request by rafapereirabr**
I would like to add the hex sticker of geobr.

geobr is an R package to download official spatial data sets of Brazil
info at https://github.com/ipeaGIT/geobr

geobr_logo_b

### CODE REVIEW

**Review by hexagontruth — CHANGES_REQUESTED** [review]
Three things:

1) You don't need to include the "filename" key in the JSON it generates that automatically, and at any rate the filename is wrong. Not a big deal but if you revise this anyway might want to just remove that line and the trailing comma from the previous line.
2) The PNG is dimensionally too large. Modern browsers will scale it down, and I assume there are some images here that don't exactly fit the size requirements, but that is what the README specifies (181x209) so that's what I am comfortable signing off on.
3) The SVG is too large spatially. I do not know how you got this to be 26MB, but I can only assume it has some extremely precise boundary lines in it. The README maximum is 500 kB, which should be more than enough for an extremely high-resolution version of this. Most SVGs here are like under 20 kB, the vast majority are under 50.

Thanks!

**Comment by rafapereirabr** [comment]
Hi Max. Thank you for your comments. I've now (1) fixed the metadata, (2) changed the `.png` logo dimensions, and (3) reduced the size of the `.svg` logo

**Review by hexagontruth — APPROVED** [review]
I'm not Max, and the raster size is still off by one pixel, but it's close enough, thanks.

**Comment by rafapereirabr** [comment]
Thanks, Graham

**Pull request merged**
