### PR TITLE
Update fedora hex to comply with the Fedora Trademark Guidelines

### PR DESCRIPTION
**Pull request by micahdenn**
Unfortunately the fedora sticker does not comply with our [Logo Usage Guidelines](https://fedoraproject.org/wiki/Logo/UsageGuidelines) and is thus in violation of the Fedora trademark.

I have updated the image to something that complies with the guidelines.

### CODE REVIEW

**Comment by jcgruenhage** [comment]
I agree that this should be merged from a legal point of view, but I think that the current file looks better than what you propose

**Comment by mairin** [comment]
@micahdenn the license is incorrect, it isn't CC-BY-SA, the license line probably should point to https://fedoraproject.org/Logo/UsageGuidelines 

This is much better in terms of compliance, I think it would look a little bit better if it was on the lighter blue BG instead of white?

**Comment by micahdenn** [comment]
@jcgruenhage so it turns out we already have a hex sticker design that is compliant and looks better. I will close this pull and make another with the proper design as soon as I get a chance.

@mairin thanks for clarification on the license.

**Comment by micahdenn** [comment]
Committed the correct design

**Comment by mairin** [comment]
@jcgruenhage can you review the new design?

**Review by jcgruenhage — APPROVED** [review]
lgtm, but I'm just a contributor without commit rights, @maxogden or @pkq should be able to help you

**Comment by mairin** [comment]
@maxogden , @pkq can you help?

**Pull request merged**
