### PR TITLE
added Privacy Badger and EFF hexagons

### PR DESCRIPTION
**Pull request by SwartzCr**

### CODE REVIEW

**Comment by max-mapper** [comment]
YESSSSS

**Comment by max-mapper** [comment]
@SwartzCr is CC0 license OK for these?

**Comment by max-mapper** [comment]
@SwartzCr oh also can you send another PR for the .svg files? So that people can get the vector art to print out their own if needed. I created JSON metadata files for the stickers in o/ commit also

**Comment by SwartzCr** [comment]
I believe all eff things are CC with attribution, but this should clarify: https://www.eff.org/copyright
and I don't have the SVG files :(
But I could try hard to get them if you thought it was really important

**Comment by max-mapper** [comment]
@SwartzCr its not super important, i just like to try and put the vector versions here so if people wanna print out stickers they can get high quality ones. ill just put a note in the description that vectors arent available and to open an issue if someone wants them

**Pull request merged**
