### PR TITLE
Node.js Hexagon

### PR DESCRIPTION
**Pull request by joshhartigan**
See #1

### CODE REVIEW

**Comment by max-mapper** [comment]
hey, thanks for the pr, but I wasn't quite ready :) I updated the readme -- can you rebase?

**Comment by joshhartigan** [comment]
sorry, I'm not great with git - how would I do that?

**Comment by max-mapper** [comment]
easiest way would be to close your pr and re-do it probably

**Comment by joshhartigan** [comment]
on it :)

**Pull request closed without merging**
