### PR TITLE
Add tidyrisk (collector and evaluator) hex stickers.

### PR DESCRIPTION
**Pull request by davidski**
Thanks for running this site! This PR adds two hex stickers for R packages in the [tidyrisk](https://tidyrisk.org) family, [collector](https://collector.tidyrisk.org) and [evaluator](https://evaluator.tidyrisk.org).

collector
evaluator

### CODE REVIEW

**Review by hexagontruth — COMMENTED** [review]
This more or less looks in order, and I'll add it as is if you think it's appropriate, but would it not make sense to namespace these under, say, "tidyrisk" (e.g. "tidyrisk-collector")?

**Comment by hexagontruth** [comment]
Also good luck reading that text on a 2'' sticker lol.

**Comment by davidski** [comment]
Thanks for the review!

For the namespace, while these two packages work together, they also provide stand alone functionality. These are related in the same way that the [tidyverse](https://www.tidyverse.org/) packages (dplyr, forcats, tibble, ggplot2, etc.) already in this collection are related. If you'd rather treat these differently and put them under a common namespace, I don't mind. :smile: Let me know if you want a modification to the PR!

**Comment by hexagontruth** [comment]
Well I don't know much about indigenous tidyverse culture, so if you think it's okay I'll take your word for it. If you want to update it in the future feel free to submit another PR.

**Pull request merged**
