### PR TITLE
Add CentOS Stickers

### PR DESCRIPTION
**Pull request by williamjmorenor**
Signed-off-by: William José Moreno Reyes <williamjmorenor@gmail.com>

### CODE REVIEW

**Comment by williamjmorenor** [comment]
centos-hex

centos-hex-symbol

**Review by hexagontruth — CHANGES_REQUESTED** [review]
Two things:
centos
1) The raster images are the wrong size. Judging from how they look against a background, I am suspecting this may be an alpha mishap? I.e., there was a white and a transparent background and somehow the image was cropped treating both as a background? Not sure.

2) Is this an approved form of the logo by CentOS? I am reading their usage guidelines (https://wiki.centos.org/ArtWork/Brand/Logo) and it doesn't seem like this color combo, &c. is part of their current styling. To be safe might I suggest only using the logotype variant?

**Comment by williamjmorenor** [comment]
I made the changes, please note that I make the border black to match the version you find in events:

https://twitter.com/redhatopen/status/690967569898037248

Please note they use the same dark blue in the background,

**Review by hexagontruth — APPROVED** [review]
Looks good enough thanks.

**Pull request merged**
